version: "3.9"
    
services:
  mysql:
    build: ./dockerfiles/mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    
  wordpress:
    depends_on:
      - mysql
    build: ./dockerfiles/wordpress
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./data/wordpress:/var/www/html

  phpmyadmin:
    build: ./dockerfiles/phpmyadmin
    restart: always
    ports:
      - 3333:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORT: root

  mailhog:
    build: ./dockerfiles/mailhog
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - ./data/mailhog:/maildir