version: "3.9"
services:
  mysql:
    build: ./dockerfiles/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    
  wordpress:
    depends_on:
      - mysql
    build: ./dockerfiles/wordpress
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
    volumes:
      - ./data/wordpress:/var/www/html

  phpmyadmin:
    build: ./dockerfiles/phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORT: "${MYSQL_ROOT_PASSWORD}"

  mailhog:
    build: ./dockerfiles/mailhog
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    ports:
      - "${MAILHOG_SMTP_PORT}:1025"
      - "${MAILHOG_UI_PORT}:8025"
    volumes:
      - ./data/mailhog:/maildir