version: "3.9"
    
services:
  db:
    build: ./dockerfiles/mysql
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    
  wordpress:
    depends_on:
      - db
    build: ./dockerfiles/wordpress
    ports:
      - 8000:80
      - 443:443
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress

  phpmyadmin:
    build: ./dockerfiles/phpmyadmin
    restart: always
    ports:
      - 3333:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORT: password

  mailhog:
    build: ./dockerfiles/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"